//LOGIN
export const LOGIN_REQUEST="LOGIN_REQUEST"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAILURE="LOGIN_FAILURE"

// LOGOUT
export const LOGOUT_REQUEST="LOGOUT_REQUEST"
export const LOGOUT_SUCCESS="LOGOUT_SUCCESS"
export const LOGOUT_FAILURE="LOGOUT_FAILURE"

// CLEAR ERROR
export const CLEAR_ERROR_REQUEST="LOGIN_ERR_REQUEST"
export const CLEAR_ERROR_SUCCESS="LOGIN_ERR_SUCCESS"
export const CLEAR_ERROR_FAILURE="LOGIN_ERR_FAILURE"

// JOIN 
export const JOIN_REQUEST="JOIN_REQUEST"
export const JOIN_SUCCESS="JOIN_SUCCESS"
export const JOIN_FAILURE="JOIN_FAILURE"

// USER LOADING
export const USER_LOADING_REQUEST="USER_LOADING_REQUEST"
export const USER_LOADING_SUCCESS="USER_LOADING_SUCCESS"
export const USER_LOADING_FAILURE="USER_LOADING_FAILURE"

//POST WRITE
export const WRITE_POST_REQUEST="WRITE_POST_REQUEST"
export const WRITE_POST_SUCCESS="WRITE_POST_SUCCESS"
export const WRITE_POST_FAILURE="WRITE_POST_FAILURE"

//POST LOADING
export const POST_LOADING_REQUEST="POST_LOADING_REQUEST"
export const POST_LOADING_SUCCESS="POST_LOADING_SUCCESS"
export const POST_LOADING_FAILURE="POST_LOADING_FAILURE"

//POST UPLOAD
export const POST_UPLOAD_REQUEST="POST_UPLOAD_REQUEST"
export const POST_UPLOAD_SUCCESS="POST_UPLOAD_SUCCESS"
export const POST_UPLOAD_FAILURE="POST_UPLOAD_FAILURE"


//POST UPLOAD
export const POST_DETAIL_LOAD_REQUEST="POST_DETAIL_LOAD_REQUEST"
export const POST_DETAIL_LOAD_SUCCESS="POST_DETAIL_LOAD_SUCCESS"
export const POST_DETAIL_LOAD_FAILURE="POST_DETAIL_LOAD_FAILURE"


//POST DELETE
export const DELETE_POST_REQUEST="DELETE_POST_REQUEST"
export const DELETE_POST_SUCCESS="DELETE_POST_SUCCESS"
export const DELETE_POST_FAILURE="DELETE_POST_FAILURE"

// LOAD COMMENT 
export const LOAD_COMMENT_REQUEST="LOAD_COMMENT_REQUEST"
export const LOAD_COMMENT_SUCCESS="LOAD_COMMENT_SUCCESS"
export const LOAD_COMMENT_FAILURE="LOAD_COMMENT_FAILURE"

// CREATE COMMENT
export const CREATE_COMMENT_REQUEST="CREATE_COMMENT_REQUEST"
export const CREATE_COMMENT_SUCCESS="CREATE_COMMENT_SUCCESS"
export const CREATE_COMMENT_FAILURE="CREATE_COMMENT_FAILURE"

// DELETE COMMENT
export const DELETE_COMMENT_REQUEST="DELETE_COMMENT_REQUEST"
export const DELETE_COMMENT_SUCCESS="DELETE_COMMENT_SUCCESS"
export const DELETE_COMMENT_FAILURE="DELETE_COMMENT_FAILURE"
