//LOGIN
export const LOGIN_REQUEST="LOGIN_REQUEST"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAILURE="LOGIN_FAILURE"

// LOGOUT
export const LOGOUT_REQUEST="LOGOUT_REQUEST"
export const LOGOUT_SUCCESS="LOGOUT_SUCCESS"
export const LOGOUT_FAILURE="LOGOUT_FAILURE"

// CLEAR ERROR
export const CLEAR_ERROR_REQUEST="LOGIN_ERR_REQUEST"
export const CLEAR_ERROR_SUCCESS="LOGIN_ERR_SUCCESS"
export const CLEAR_ERROR_FAILURE="LOGIN_ERR_FAILURE"

// JOIN 
export const JOIN_REQUEST="JOIN_REQUEST"
export const JOIN_SUCCESS="JOIN_SUCCESS"
export const JOIN_FAILURE="JOIN_FAILURE"

// USER LOADING
export const USER_LOADING_REQUEST="USER_LOADING_REQUEST"
export const USER_LOADING_SUCCESS="USER_LOADING_SUCCESS"
export const USER_LOADING_FAILURE="USER_LOADING_FAILURE"

//POST WRITE
export const POST_WRITE_REQUEST="POST_WRITE_REQUEST"
export const POST_WRITE_SUCCESS="POST_WRITE_SUCCESS"
export const POST_WRITE_FAILURE="POST_WRITE_FAILURE"

//POST LOADING
export const POST_LOADING_REQUEST="POST_LOADING_REQUEST"
export const POST_LOADING_SUCCESS="POST_LOADING_SUCCESS"
export const POST_LOADING_FAILURE="POST_LOADING_FAILURE"